REQUIRED_SHEETS = ['SOC', 'JGS', 'RLC', 'CEB', 'RRHI']

from copy import deepcopy


BUSINESS_UNIT_SHEETS = ['SOC', 'JGS', 'RLC', 'CEB', 'RRHI']


def _clone_spec(spec):
    return deepcopy(spec)


SOURCE_SPECS = {
    'SOC': {
        'header_sequence': [
            'Company Code', 'Company Name', 'Fiscal year', 'Vendor Code', 'Vendor Name', 'Vendor Account Group',
            'Accounting Document Number', 'Reference Document', 'Material document', 'Plant', 'Payment Year',
            'Payment Document', 'Check Number', 'AP User ID', 'AP Username', 'AP Department', 'CP User ID',
            'CP Username', 'CP Department', 'Assignment', 'Payment Document Typ', 'Invoice Ref Key 3',
            'Payment Ref Key 1', 'OR Date', 'OR Number', 'Document Currency', 'Document Type', 'Payment Method',
            'Pmt Method Description', 'Payment Terms', 'Document Date', 'Baseline Date', 'Posting Date',
            'Date to BCD', 'Clearing', 'Payment Release Date', 'Encashment Date', 'Net due date', 'POT',
            'Nature of Transaction', 'Process Group', 'AP Status', 'AP Status Description', 'Status Date',
            'Amount', 'Amount in Doc Currency', 'Days of Status', 'AP PCT (Post to Rele', 'AP TAT (Pos to Clear',
            'IV to Countering', 'Countering to Posting', 'Posting to BCD', 'BCD to Clearing', 'Clearing to Releasing',
            'Countering to Releasing',
        ],
        'required_headers': [
            'Company Code', 'Fiscal year', 'Vendor Code', 'Vendor Name', 'Accounting Document Number',
            'Payment Document', 'Payment Method', 'Document Date', 'Posting Date', 'Net due date', 'Status Date', 'Amount',
        ],
        'date_fields': ['OR Date', 'Document Date', 'Baseline Date', 'Posting Date', 'Date to BCD', 'Clearing', 'Payment Release Date', 'Encashment Date', 'Net due date', 'Status Date'],
        'duplicate_key_fields': ['Company Code', 'Accounting Document Number', 'Vendor Code', 'Amount', 'Posting Date'],
        'record_class_fields': ['Process Group', 'Nature of Transaction', 'Document Type'],
        'canonical_map': {
            'company_code': 'Company Code',
            'vendor_code': 'Vendor Code',
            'vendor_name': 'Vendor Name',
            'fiscal_year': 'Fiscal year',
            'payment_document': 'Payment Document',
            'accounting_document': 'Accounting Document Number',
            'payment_method': 'Payment Method',
            'document_type': 'Document Type',
            'process_group': 'Process Group',
            'nature_of_transaction': 'Nature of Transaction',
            'status_code': 'AP Status',
            'status_description': 'AP Status Description',
            'document_date': 'Document Date',
            'baseline_date': 'Baseline Date',
            'posting_date': 'Posting Date',
            'payment_entry_date': 'Date to BCD',
            'payment_release_date': 'Payment Release Date',
            'clearing_date': 'Clearing',
            'net_due_date': 'Net due date',
            'status_date': 'Status Date',
            'amount_local': 'Amount',
            'amount_document': 'Amount in Doc Currency',
            'days_of_status': 'Days of Status',
            'pot': 'POT',
            'payment_cycle_time': 'AP PCT (Post to Rele',
            'total_processing_time': 'AP TAT (Pos to Clear',
        },
    },
    'JGS': {
        'header_sequence': [
            'Company Code', 'Company Name', 'Fiscal year', 'Vendor Code', 'Vendor Name', 'Vendor Account Group',
            'Vendor Account Group', 'Process Group', 'Nature of Transaction', 'Reference Document', 'Payment Year',
            'Terms of Payment', 'SAP Document Number', 'Payment Document', 'Document type', 'Document type Desc',
            'Payment Method', 'Check Number', 'Check Status', 'Document Date', 'Base Date', 'VIM Entered Date',
            'SAP Document Posting date', 'Unblocking Date', 'Payment Entry Date', 'SAP Document Clearing Date',
            'Payment Readiness Dt', 'Payment Release Date', 'OR Submission Date', 'Net Due date', 'Adjusted Net Due Date',
            'Item', 'DP Document', 'Assignment', 'GR Document', 'Doc Header Text', 'Item Text', 'AP User ID',
            'CP User ID', 'Pmt Doc Ref Key 1', 'ODA Clearing Documen', 'Plant', 'Account Holder Name',
            'Bank Account Number', 'Bank Key', 'Bank Name', 'Bank Reference', 'Status', 'Status Description',
            'Status Date', 'Amount in Local Curr', 'Days (Term 1)', 'Days (Term 2)', 'Days (Term 3)', 'Days of Status',
            'SLA Difference', 'POT', 'AP TAT', 'CP TAT', 'TR TAT', 'Payment Cycle Time', 'Total Processing Time',
        ],
        'required_headers': [
            'Company Code', 'Fiscal year', 'Vendor Code', 'Vendor Name', 'SAP Document Number', 'Payment Document',
            'Payment Method', 'Document Date', 'SAP Document Posting date', 'Adjusted Net Due Date', 'Status Date', 'Amount in Local Curr',
        ],
        'date_fields': ['Document Date', 'Base Date', 'VIM Entered Date', 'SAP Document Posting date', 'Unblocking Date', 'Payment Entry Date', 'SAP Document Clearing Date', 'Payment Readiness Dt', 'Payment Release Date', 'OR Submission Date', 'Net Due date', 'Adjusted Net Due Date', 'Status Date'],
        'duplicate_key_fields': ['Company Code', 'SAP Document Number', 'Vendor Code', 'Amount in Local Curr', 'SAP Document Posting date'],
        'record_class_fields': ['Process Group', 'Document type Desc', 'Doc Header Text', 'Item Text'],
        'canonical_map': {
            'company_code': 'Company Code',
            'vendor_code': 'Vendor Code',
            'vendor_name': 'Vendor Name',
            'fiscal_year': 'Fiscal year',
            'payment_document': 'Payment Document',
            'accounting_document': 'SAP Document Number',
            'payment_method': 'Payment Method',
            'document_type': 'Document type',
            'process_group': 'Process Group',
            'nature_of_transaction': 'Nature of Transaction',
            'status_code': 'Status',
            'status_description': 'Status Description',
            'document_date': 'Document Date',
            'baseline_date': 'Base Date',
            'posting_date': 'SAP Document Posting date',
            'payment_entry_date': 'Payment Entry Date',
            'payment_release_date': 'Payment Release Date',
            'clearing_date': 'SAP Document Clearing Date',
            'net_due_date': 'Adjusted Net Due Date',
            'status_date': 'Status Date',
            'amount_local': 'Amount in Local Curr',
            'amount_document': 'Amount in Local Curr',
            'days_of_status': 'Days of Status',
            'pot': 'POT',
            'payment_cycle_time': 'Payment Cycle Time',
            'total_processing_time': 'Total Processing Time',
        },
    },
    'RLC': _clone_spec({
        'header_sequence': [
            'Company Code', 'Company Name', 'Fiscal year', 'Vendor Code', 'Vendor Name', 'Vendor Account Group',
            'Vendor Account Group', 'Process Group', 'Nature of Transaction', 'Reference Document', 'Payment Year',
            'Terms of Payment', 'SAP Document Number', 'Payment Document', 'Document type', 'Document type Desc',
            'Payment Method', 'Check Number', 'Check Status', 'Document Date', 'Base Date', 'VIM Entered Date',
            'SAP Document Posting date', 'Unblocking Date', 'Payment Entry Date', 'SAP Document Clearing Date',
            'Payment Readiness Dt', 'Payment Release Date', 'OR Submission Date', 'Net Due date', 'Adjusted Net Due Date',
            'Item', 'DP Document', 'Assignment', 'GR Document', 'Doc Header Text', 'Item Text', 'AP User ID',
            'CP User ID', 'Pmt Doc Ref Key 1', 'ODA Clearing Documen', 'Plant', 'Account Holder Name',
            'Bank Account Number', 'Bank Key', 'Bank Name', 'Bank Reference', 'Status', 'Status Description',
            'Status Date', 'Amount in Local Curr', 'Days (Term 1)', 'Days (Term 2)', 'Days (Term 3)', 'Days of Status',
            'SLA Difference', 'POT', 'AP TAT', 'CP TAT', 'TR TAT', 'Payment Cycle Time', 'Total Processing Time',
        ],
        'required_headers': [
            'Company Code', 'Fiscal year', 'Vendor Code', 'Vendor Name', 'SAP Document Number', 'Payment Document',
            'Payment Method', 'Document Date', 'SAP Document Posting date', 'Adjusted Net Due Date', 'Status Date', 'Amount in Local Curr',
        ],
        'date_fields': ['Document Date', 'Base Date', 'VIM Entered Date', 'SAP Document Posting date', 'Unblocking Date', 'Payment Entry Date', 'SAP Document Clearing Date', 'Payment Readiness Dt', 'Payment Release Date', 'OR Submission Date', 'Net Due date', 'Adjusted Net Due Date', 'Status Date'],
        'duplicate_key_fields': ['Company Code', 'SAP Document Number', 'Vendor Code', 'Amount in Local Curr', 'SAP Document Posting date'],
        'record_class_fields': ['Process Group', 'Document type Desc', 'Doc Header Text', 'Item Text'],
        'canonical_map': {
            'company_code': 'Company Code',
            'vendor_code': 'Vendor Code',
            'vendor_name': 'Vendor Name',
            'fiscal_year': 'Fiscal year',
            'payment_document': 'Payment Document',
            'accounting_document': 'SAP Document Number',
            'payment_method': 'Payment Method',
            'document_type': 'Document type',
            'process_group': 'Process Group',
            'nature_of_transaction': 'Nature of Transaction',
            'status_code': 'Status',
            'status_description': 'Status Description',
            'document_date': 'Document Date',
            'baseline_date': 'Base Date',
            'posting_date': 'SAP Document Posting date',
            'payment_entry_date': 'Payment Entry Date',
            'payment_release_date': 'Payment Release Date',
            'clearing_date': 'SAP Document Clearing Date',
            'net_due_date': 'Adjusted Net Due Date',
            'status_date': 'Status Date',
            'amount_local': 'Amount in Local Curr',
            'amount_document': 'Amount in Local Curr',
            'days_of_status': 'Days of Status',
            'pot': 'POT',
            'payment_cycle_time': 'Payment Cycle Time',
            'total_processing_time': 'Total Processing Time',
        },
    }),
    'CEB': _clone_spec({
        'header_sequence': [
            'Company Code', 'Company Name', 'Fiscal year', 'Vendor Code', 'Vendor Name', 'Vendor Account Group',
            'Vendor Account Group', 'Process Group', 'Nature of Transaction', 'Reference Document', 'Payment Year',
            'Terms of Payment', 'SAP Document Number', 'Payment Document', 'Document type', 'Document type Desc',
            'Payment Method', 'Check Number', 'Check Status', 'Document Date', 'Base Date', 'VIM Entered Date',
            'SAP Document Posting date', 'Unblocking Date', 'Payment Entry Date', 'SAP Document Clearing Date',
            'Payment Readiness Dt', 'Payment Release Date', 'OR Submission Date', 'Net Due date', 'Adjusted Net Due Date',
            'Item', 'DP Document', 'Assignment', 'GR Document', 'Doc Header Text', 'Item Text', 'AP User ID',
            'CP User ID', 'Pmt Doc Ref Key 1', 'ODA Clearing Documen', 'Plant', 'Account Holder Name',
            'Bank Account Number', 'Bank Key', 'Bank Name', 'Bank Reference', 'Status', 'Status Description',
            'Status Date', 'Amount in Local Curr', 'Days (Term 1)', 'Days (Term 2)', 'Days (Term 3)', 'Days of Status',
            'SLA Difference', 'POT', 'AP TAT', 'CP TAT', 'TR TAT', 'Payment Cycle Time', 'Total Processing Time',
        ],
        'required_headers': [
            'Company Code', 'Fiscal year', 'Vendor Code', 'Vendor Name', 'SAP Document Number', 'Payment Document',
            'Payment Method', 'Document Date', 'SAP Document Posting date', 'Adjusted Net Due Date', 'Status Date', 'Amount in Local Curr',
        ],
        'date_fields': ['Document Date', 'Base Date', 'VIM Entered Date', 'SAP Document Posting date', 'Unblocking Date', 'Payment Entry Date', 'SAP Document Clearing Date', 'Payment Readiness Dt', 'Payment Release Date', 'OR Submission Date', 'Net Due date', 'Adjusted Net Due Date', 'Status Date'],
        'duplicate_key_fields': ['Company Code', 'SAP Document Number', 'Vendor Code', 'Amount in Local Curr', 'SAP Document Posting date'],
        'record_class_fields': ['Process Group', 'Document type Desc', 'Doc Header Text', 'Item Text'],
        'canonical_map': {
            'company_code': 'Company Code',
            'vendor_code': 'Vendor Code',
            'vendor_name': 'Vendor Name',
            'fiscal_year': 'Fiscal year',
            'payment_document': 'Payment Document',
            'accounting_document': 'SAP Document Number',
            'payment_method': 'Payment Method',
            'document_type': 'Document type',
            'process_group': 'Process Group',
            'nature_of_transaction': 'Nature of Transaction',
            'status_code': 'Status',
            'status_description': 'Status Description',
            'document_date': 'Document Date',
            'baseline_date': 'Base Date',
            'posting_date': 'SAP Document Posting date',
            'payment_entry_date': 'Payment Entry Date',
            'payment_release_date': 'Payment Release Date',
            'clearing_date': 'SAP Document Clearing Date',
            'net_due_date': 'Adjusted Net Due Date',
            'status_date': 'Status Date',
            'amount_local': 'Amount in Local Curr',
            'amount_document': 'Amount in Local Curr',
            'days_of_status': 'Days of Status',
            'pot': 'POT',
            'payment_cycle_time': 'Payment Cycle Time',
            'total_processing_time': 'Total Processing Time',
        },
    }),
    'RRHI': _clone_spec({
        'header_sequence': [
            'Company Code', 'Company Name', 'Fiscal year', 'Vendor Code', 'Vendor Name', 'Vendor Account Group',
            'Vendor Account Group', 'Process Group', 'Nature of Transaction', 'Reference Document', 'Payment Year',
            'Terms of Payment', 'SAP Document Number', 'Payment Document', 'Document type', 'Document type Desc',
            'Payment Method', 'Check Number', 'Check Status', 'Document Date', 'Base Date', 'VIM Entered Date',
            'SAP Document Posting date', 'Unblocking Date', 'Payment Entry Date', 'SAP Document Clearing Date',
            'Payment Readiness Dt', 'Payment Release Date', 'OR Submission Date', 'Net Due date', 'Adjusted Net Due Date',
            'Item', 'DP Document', 'Assignment', 'GR Document', 'Doc Header Text', 'Item Text', 'AP User ID',
            'CP User ID', 'Pmt Doc Ref Key 1', 'ODA Clearing Documen', 'Plant', 'Account Holder Name',
            'Bank Account Number', 'Bank Key', 'Bank Name', 'Bank Reference', 'Status', 'Status Description',
            'Status Date', 'Amount in Local Curr', 'Days (Term 1)', 'Days (Term 2)', 'Days (Term 3)', 'Days of Status',
            'SLA Difference', 'POT', 'AP TAT', 'CP TAT', 'TR TAT', 'Payment Cycle Time', 'Total Processing Time',
        ],
        'required_headers': [
            'Company Code', 'Fiscal year', 'Vendor Code', 'Vendor Name', 'SAP Document Number', 'Payment Document',
            'Payment Method', 'Document Date', 'SAP Document Posting date', 'Adjusted Net Due Date', 'Status Date', 'Amount in Local Curr',
        ],
        'date_fields': ['Document Date', 'Base Date', 'VIM Entered Date', 'SAP Document Posting date', 'Unblocking Date', 'Payment Entry Date', 'SAP Document Clearing Date', 'Payment Readiness Dt', 'Payment Release Date', 'OR Submission Date', 'Net Due date', 'Adjusted Net Due Date', 'Status Date'],
        'duplicate_key_fields': ['Company Code', 'SAP Document Number', 'Vendor Code', 'Amount in Local Curr', 'SAP Document Posting date'],
        'record_class_fields': ['Process Group', 'Document type Desc', 'Doc Header Text', 'Item Text'],
        'canonical_map': {
            'company_code': 'Company Code',
            'vendor_code': 'Vendor Code',
            'vendor_name': 'Vendor Name',
            'fiscal_year': 'Fiscal year',
            'payment_document': 'Payment Document',
            'accounting_document': 'SAP Document Number',
            'payment_method': 'Payment Method',
            'document_type': 'Document type',
            'process_group': 'Process Group',
            'nature_of_transaction': 'Nature of Transaction',
            'status_code': 'Status',
            'status_description': 'Status Description',
            'document_date': 'Document Date',
            'baseline_date': 'Base Date',
            'posting_date': 'SAP Document Posting date',
            'payment_entry_date': 'Payment Entry Date',
            'payment_release_date': 'Payment Release Date',
            'clearing_date': 'SAP Document Clearing Date',
            'net_due_date': 'Adjusted Net Due Date',
            'status_date': 'Status Date',
            'amount_local': 'Amount in Local Curr',
            'amount_document': 'Amount in Local Curr',
            'days_of_status': 'Days of Status',
            'pot': 'POT',
            'payment_cycle_time': 'Payment Cycle Time',
            'total_processing_time': 'Total Processing Time',
        },
    }),
}

STARTER_CONTROLS = [
    {
        'control_id': 'ALL-LIFECYCLE-DATE-ORDER',
        'name': 'Lifecycle dates in logical order',
        'worksheet_scope': 'ALL',
        'template_type': 'date_order',
        'severity': 'HIGH',
        'owner_role': 'AP Control Owner',
        'description': 'Flags records whose critical lifecycle dates move backward in time.',
        'parameters_json': {'pairs': [['document_date', 'posting_date'], ['baseline_date', 'net_due_date'], ['posting_date', 'payment_release_date'], ['payment_release_date', 'clearing_date']], 'record_class': 'base_transaction'},
        'version': 1,
        'display_order': 10,
    },
    {
        'control_id': 'ALL-NON-NEGATIVE-METRICS',
        'name': 'Cycle-time metrics within plausible range',
        'worksheet_scope': 'ALL',
        'template_type': 'non_negative_metric',
        'severity': 'HIGH',
        'owner_role': 'Process Owner',
        'description': 'Flags negative or implausibly high TAT values.',
        'parameters_json': {'record_class': 'base_transaction', 'fields': {'days_of_status': {'min': 0, 'max': 180}, 'payment_cycle_time': {'min': 0, 'max': 365}, 'total_processing_time': {'min': 0, 'max': 365}}},
        'version': 1,
        'display_order': 20,
    },
    {
        'control_id': 'ALL-AGING-BREACH',
        'name': 'Aging over threshold',
        'worksheet_scope': 'ALL',
        'template_type': 'age_over_threshold',
        'severity': 'MEDIUM',
        'owner_role': 'Remediation Owner',
        'description': 'Flags backlog items aging beyond threshold days.',
        'parameters_json': {'field': 'days_of_status', 'threshold': 30, 'exclude_status_contains': ['clear', 'closed', 'released'], 'record_class': 'base_transaction'},
        'version': 1,
        'display_order': 30,
    },
    {
        'control_id': 'ALL-DUPLICATE-TRANSACTION-KEY',
        'name': 'Duplicate transaction candidates',
        'worksheet_scope': 'ALL',
        'template_type': 'duplicate_key',
        'severity': 'HIGH',
        'owner_role': 'Continuous Audit COE',
        'description': 'Flags duplicate normalized transaction keys in a run.',
        'parameters_json': {'field': 'transaction_key', 'record_class': 'base_transaction'},
        'version': 1,
        'display_order': 40,
    },
    {
        'control_id': 'ALL-PLACEHOLDER-SPIKE',
        'name': 'Placeholder density spike',
        'worksheet_scope': 'ALL',
        'template_type': 'placeholder_spike',
        'severity': 'MEDIUM',
        'owner_role': 'Data Owner',
        'description': 'Flags columns whose placeholder rate is high or spikes week over week.',
        'parameters_json': {'threshold': 0.20, 'delta_threshold': 0.10},
        'version': 1,
        'display_order': 50,
    },
    {
        'control_id': 'SOC-CHECK-REFERENCE-REQUIRED',
        'name': 'SOC check payments need reference details',
        'worksheet_scope': 'SOC',
        'template_type': 'required_when',
        'severity': 'HIGH',
        'owner_role': 'AP Control Owner',
        'description': 'Requires key reference fields for check-based SOC payments.',
        'parameters_json': {'record_class': 'base_transaction', 'when': [{'field': 'payment_method', 'op': 'icontains', 'value': 'check'}], 'required_fields': ['Check Number', 'OR Number', 'payment_release_date']},
        'version': 1,
        'display_order': 60,
    },
    {
        'control_id': 'JGS-CHECK-REFERENCE-REQUIRED',
        'name': 'JGS check payments need check details',
        'worksheet_scope': 'JGS',
        'template_type': 'required_when',
        'severity': 'HIGH',
        'owner_role': 'AP Control Owner',
        'description': 'Requires check details for check-based JGS payments.',
        'parameters_json': {'record_class': 'base_transaction', 'when': [{'field': 'payment_method', 'op': 'icontains', 'value': 'check'}], 'required_fields': ['Check Number', 'payment_release_date']},
        'version': 1,
        'display_order': 70,
    },
    {
        'control_id': 'JGS-BANK-REFERENCE-REQUIRED',
        'name': 'JGS transfer payments need bank reference',
        'worksheet_scope': 'JGS',
        'template_type': 'required_when',
        'severity': 'MEDIUM',
        'owner_role': 'Treasury Owner',
        'description': 'Requires bank reference for transfer-based JGS payments.',
        'parameters_json': {'record_class': 'base_transaction', 'when': [{'field': 'payment_method', 'op': 'icontains', 'value': 'transfer'}], 'required_fields': ['Bank Reference']},
        'version': 1,
        'display_order': 80,
    },
    {
        'control_id': 'RLC-CHECK-REFERENCE-REQUIRED',
        'name': 'RLC check payments need check details',
        'worksheet_scope': 'RLC',
        'template_type': 'required_when',
        'severity': 'HIGH',
        'owner_role': 'AP Control Owner',
        'description': 'Requires check details for check-based RLC payments.',
        'parameters_json': {'record_class': 'base_transaction', 'when': [{'field': 'payment_method', 'op': 'icontains', 'value': 'check'}], 'required_fields': ['Check Number', 'payment_release_date']},
        'version': 1,
        'display_order': 81,
    },
    {
        'control_id': 'RLC-BANK-REFERENCE-REQUIRED',
        'name': 'RLC transfer payments need bank reference',
        'worksheet_scope': 'RLC',
        'template_type': 'required_when',
        'severity': 'MEDIUM',
        'owner_role': 'Treasury Owner',
        'description': 'Requires bank reference for transfer-based RLC payments.',
        'parameters_json': {'record_class': 'base_transaction', 'when': [{'field': 'payment_method', 'op': 'icontains', 'value': 'transfer'}], 'required_fields': ['Bank Reference']},
        'version': 1,
        'display_order': 82,
    },
    {
        'control_id': 'CEB-CHECK-REFERENCE-REQUIRED',
        'name': 'CEB check payments need check details',
        'worksheet_scope': 'CEB',
        'template_type': 'required_when',
        'severity': 'HIGH',
        'owner_role': 'AP Control Owner',
        'description': 'Requires check details for check-based CEB payments.',
        'parameters_json': {'record_class': 'base_transaction', 'when': [{'field': 'payment_method', 'op': 'icontains', 'value': 'check'}], 'required_fields': ['Check Number', 'payment_release_date']},
        'version': 1,
        'display_order': 83,
    },
    {
        'control_id': 'CEB-BANK-REFERENCE-REQUIRED',
        'name': 'CEB transfer payments need bank reference',
        'worksheet_scope': 'CEB',
        'template_type': 'required_when',
        'severity': 'MEDIUM',
        'owner_role': 'Treasury Owner',
        'description': 'Requires bank reference for transfer-based CEB payments.',
        'parameters_json': {'record_class': 'base_transaction', 'when': [{'field': 'payment_method', 'op': 'icontains', 'value': 'transfer'}], 'required_fields': ['Bank Reference']},
        'version': 1,
        'display_order': 84,
    },
    {
        'control_id': 'RRHI-CHECK-REFERENCE-REQUIRED',
        'name': 'RRHI check payments need check details',
        'worksheet_scope': 'RRHI',
        'template_type': 'required_when',
        'severity': 'HIGH',
        'owner_role': 'AP Control Owner',
        'description': 'Requires check details for check-based RRHI payments.',
        'parameters_json': {'record_class': 'base_transaction', 'when': [{'field': 'payment_method', 'op': 'icontains', 'value': 'check'}], 'required_fields': ['Check Number', 'payment_release_date']},
        'version': 1,
        'display_order': 85,
    },
    {
        'control_id': 'RRHI-BANK-REFERENCE-REQUIRED',
        'name': 'RRHI transfer payments need bank reference',
        'worksheet_scope': 'RRHI',
        'template_type': 'required_when',
        'severity': 'MEDIUM',
        'owner_role': 'Treasury Owner',
        'description': 'Requires bank reference for transfer-based RRHI payments.',
        'parameters_json': {'record_class': 'base_transaction', 'when': [{'field': 'payment_method', 'op': 'icontains', 'value': 'transfer'}], 'required_fields': ['Bank Reference']},
        'version': 1,
        'display_order': 86,
    },
    {
        'control_id': 'ALL-RECURRENCE-WINDOW',
        'name': 'Recent repeat exceptions',
        'worksheet_scope': 'ALL',
        'template_type': 'recurrence_window',
        'severity': 'MEDIUM',
        'owner_role': 'IA Governance',
        'description': 'Flags records that recur within a recent lookback window.',
        'parameters_json': {'days': 60, 'record_class': 'base_transaction'},
        'version': 1,
        'display_order': 90,
    },
]
