from datetime import timedelta

from django.utils import timezone

from auditpilot.models import ControlCatalog, ControlExecution, ControlExecutionStatus, ExceptionEvent, ExceptionRecord, ExceptionStatusChoices
from auditpilot.services.constants import REQUIRED_SHEETS, STARTER_CONTROLS
from auditpilot.services.utils import stable_hash


def ensure_starter_controls():
    for control in STARTER_CONTROLS:
        ControlCatalog.objects.update_or_create(control_id=control['control_id'], defaults=control)


def get_record_value(record, field_name):
    if hasattr(record, field_name):
        return getattr(record, field_name)
    return record.source_payload.get(field_name)


def match_condition(record, condition):
    actual = get_record_value(record, condition['field'])
    expected = condition.get('value')
    operator = condition.get('op', 'eq')
    actual_text = '' if actual is None else str(actual)
    if operator == 'eq':
        return actual == expected
    if operator == 'ne':
        return actual != expected
    if operator == 'icontains':
        return str(expected).lower() in actual_text.lower()
    if operator == 'contains':
        return str(expected) in actual_text
    if operator == 'in':
        return actual in condition.get('value', [])
    return False


def _create_exception(run, control, sheet_name, finding):
    exception = ExceptionRecord.objects.create(
        run=run,
        control=control,
        normalized_record=finding.get('normalized_record'),
        recurrence_of_id=finding.get('recurrence_of'),
        entity=sheet_name,
        record_fingerprint=finding.get('record_fingerprint') or stable_hash([sheet_name, finding.get('title'), finding.get('detail')]),
        severity=control.severity,
        title=finding['title'],
        detail=finding.get('detail', ''),
        status=ExceptionStatusChoices.NEW,
        extra_context=finding.get('extra_context', {}),
    )
    ExceptionEvent.objects.create(exception=exception, event_type='system_create', note='Exception generated by rule engine')
    return exception


def _filter_records(records, record_class=None):
    if not record_class:
        return records
    return [record for record in records if record.record_class == record_class]


def evaluate_required_when(control, records):
    findings = []
    params = control.parameters_json
    records = _filter_records(records, params.get('record_class'))
    for record in records:
        if all(match_condition(record, condition) for condition in params.get('when', [])):
            missing = [field for field in params.get('required_fields', []) if not get_record_value(record, field)]
            if missing:
                findings.append({'normalized_record': record, 'record_fingerprint': record.record_fingerprint, 'title': 'Missing mandatory references', 'detail': f"Missing fields: {', '.join(missing)} for payment method {record.payment_method or 'unknown'}."})
    return findings


def evaluate_date_order(control, records):
    findings = []
    params = control.parameters_json
    records = _filter_records(records, params.get('record_class'))
    for record in records:
        for start_field, end_field in params.get('pairs', []):
            start_value = getattr(record, start_field, None)
            end_value = getattr(record, end_field, None)
            if start_value and end_value and start_value > end_value:
                findings.append({'normalized_record': record, 'record_fingerprint': record.record_fingerprint, 'title': 'Lifecycle dates out of order', 'detail': f"{start_field} ({start_value}) occurs after {end_field} ({end_value})."})
    return findings


def evaluate_non_negative_metric(control, records):
    findings = []
    params = control.parameters_json
    records = _filter_records(records, params.get('record_class'))
    for record in records:
        for field_name, limits in params.get('fields', {}).items():
            value = getattr(record, field_name, None)
            if value is None:
                continue
            minimum = limits.get('min')
            maximum = limits.get('max')
            if (minimum is not None and value < minimum) or (maximum is not None and value > maximum):
                findings.append({'normalized_record': record, 'record_fingerprint': record.record_fingerprint, 'title': 'Metric outside expected range', 'detail': f"{field_name} has value {value}, outside {minimum} to {maximum}."})
    return findings


def evaluate_age_over_threshold(control, records):
    findings = []
    params = control.parameters_json
    records = _filter_records(records, params.get('record_class'))
    threshold = params.get('threshold', 0)
    exclude_terms = [term.lower() for term in params.get('exclude_status_contains', [])]
    for record in records:
        value = getattr(record, params.get('field', 'days_of_status'), None)
        status_text = (record.status_description or record.status_code or '').lower()
        if value is not None and value > threshold and not any(term in status_text for term in exclude_terms):
            findings.append({'normalized_record': record, 'record_fingerprint': record.record_fingerprint, 'title': 'Aging threshold exceeded', 'detail': f"Days of status is {value}, above threshold {threshold}."})
    return findings


def evaluate_duplicate_key(control, records):
    params = control.parameters_json
    field_name = params.get('field', 'transaction_key')
    records = _filter_records(records, params.get('record_class'))
    grouped = {}
    for record in records:
        grouped.setdefault(getattr(record, field_name), []).append(record)
    findings = []
    for key, bucket in grouped.items():
        if key and len(bucket) > 1:
            row_ids = [record.source_row_number for record in bucket]
            for record in bucket:
                findings.append({'normalized_record': record, 'record_fingerprint': record.record_fingerprint, 'title': 'Duplicate transaction candidate', 'detail': f"Normalized key repeats across rows {row_ids}."})
    return findings


def evaluate_placeholder_spike(sheet_run):
    findings = []
    for flag in sheet_run.metrics_json.get('placeholder_flags', []):
        previous_ratio = flag.get('previous_ratio')
        if previous_ratio is None:
            detail = f"{flag['column']} placeholder ratio is {flag['ratio']:.0%} (no previous baseline)."
        else:
            detail = f"{flag['column']} placeholder ratio is {flag['ratio']:.0%} (previous {previous_ratio:.0%})."
        findings.append(
            {
                'record_fingerprint': stable_hash([sheet_run.sheet_name, flag['column']]),
                'title': 'Placeholder density warning',
                'detail': detail,
                'extra_context': flag,
            }
        )
    return findings


def evaluate_recurrence_window(control, run, records):
    findings = []
    params = control.parameters_json
    records = _filter_records(records, params.get('record_class'))
    cutoff = timezone.now() - timedelta(days=params.get('days', 60))
    recent_prior = {}
    for prior in (
        ExceptionRecord.objects.filter(opened_at__gte=cutoff)
        .exclude(run=run)
        .values('id', 'record_fingerprint', 'opened_at')
        .order_by('-opened_at')
    ):
        recent_prior.setdefault(
            prior['record_fingerprint'],
            prior,
        )
    for record in records:
        prior = recent_prior.get(record.record_fingerprint)
        if prior:
            findings.append({'normalized_record': record, 'record_fingerprint': record.record_fingerprint, 'title': 'Recurring exception pattern', 'detail': f"Record fingerprint matched prior exception opened on {prior['opened_at'].date()}.", 'recurrence_of': prior['id']})
    return findings


def run_controls_for_run(run):
    ensure_starter_controls()
    controls = ControlCatalog.objects.filter(enabled=True).order_by('display_order', 'control_id')
    records_by_sheet = {sheet: list(run.normalized_records.filter(entity=sheet)) for sheet in REQUIRED_SHEETS}
    sheet_runs = {sheet_run.sheet_name: sheet_run for sheet_run in run.sheet_runs.all()}
    total_findings = 0
    for control in controls:
        scopes = REQUIRED_SHEETS if control.worksheet_scope == 'ALL' else [control.worksheet_scope]
        for sheet_name in scopes:
            try:
                if control.template_type == 'required_when':
                    findings = evaluate_required_when(control, records_by_sheet.get(sheet_name, []))
                elif control.template_type == 'date_order':
                    findings = evaluate_date_order(control, records_by_sheet.get(sheet_name, []))
                elif control.template_type == 'non_negative_metric':
                    findings = evaluate_non_negative_metric(control, records_by_sheet.get(sheet_name, []))
                elif control.template_type == 'age_over_threshold':
                    findings = evaluate_age_over_threshold(control, records_by_sheet.get(sheet_name, []))
                elif control.template_type == 'duplicate_key':
                    findings = evaluate_duplicate_key(control, records_by_sheet.get(sheet_name, []))
                elif control.template_type == 'placeholder_spike':
                    findings = evaluate_placeholder_spike(sheet_runs.get(sheet_name)) if sheet_runs.get(sheet_name) else []
                elif control.template_type == 'recurrence_window':
                    findings = evaluate_recurrence_window(control, run, records_by_sheet.get(sheet_name, []))
                else:
                    findings = []
                for finding in findings:
                    _create_exception(run, control, sheet_name, finding)
                ControlExecution.objects.create(run=run, control=control, sheet_name=sheet_name, status=ControlExecutionStatus.SUCCEEDED, finding_count=len(findings), details_json={'template_type': control.template_type}, completed_at=timezone.now())
                total_findings += len(findings)
            except Exception as exc:
                ControlExecution.objects.create(run=run, control=control, sheet_name=sheet_name, status=ControlExecutionStatus.FAILED, finding_count=0, details_json={'error': str(exc)}, completed_at=timezone.now())
    return total_findings
