# Generated by Django 5.2.12 on 2026-03-06 08:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED_DQ', 'Failed - Data Quality'), ('FAILED_PROCESSING', 'Failed - Processing')], default='PENDING', max_length=24)),
                ('as_of_label', models.CharField(blank=True, max_length=120)),
                ('uploaded_by', models.CharField(blank=True, max_length=120)),
                ('overall_message', models.TextField(blank=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('total_exceptions', models.PositiveIntegerField(default=0)),
                ('total_warnings', models.PositiveIntegerField(default=0)),
                ('total_errors', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ControlCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('worksheet_scope', models.CharField(max_length=40)),
                ('template_type', models.CharField(choices=[('required_when', 'Required when'), ('date_order', 'Date order'), ('non_negative_metric', 'Non-negative metric'), ('age_over_threshold', 'Age over threshold'), ('duplicate_key', 'Duplicate key'), ('placeholder_spike', 'Placeholder spike'), ('recurrence_window', 'Recurrence window'), ('dq_finding', 'DQ finding')], max_length=40)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=16)),
                ('owner_role', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('parameters_json', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'control_id'],
            },
        ),
        migrations.CreateModel(
            name='SourceFileArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('stored_file', models.FileField(upload_to='raw_snapshots/%Y/%m/%d')),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('uploaded_by', models.CharField(blank=True, max_length=120)),
                ('as_of_label', models.CharField(blank=True, max_length=120)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControlExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('SUCCEEDED', 'Succeeded'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], default='SUCCEEDED', max_length=16)),
                ('finding_count', models.PositiveIntegerField(default=0)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='auditpilot.controlcatalog')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_executions', to='auditpilot.auditrun')),
            ],
            options={
                'ordering': ['sheet_name', 'control__display_order', 'control__control_id'],
            },
        ),
        migrations.CreateModel(
            name='ExceptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('entity', models.CharField(max_length=40)),
                ('record_fingerprint', models.CharField(db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('OPEN', 'Open'), ('VALIDATED', 'Validated'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='NEW', max_length=24)),
                ('disposition', models.CharField(choices=[('UNDER_REVIEW', 'Under review'), ('ISSUE_REMEDIATE', 'Issue - Remediate'), ('ISSUE_ACCEPTED', 'Issue - Accept risk / exception'), ('DQ_DEFECT', 'Not an issue - Data quality defect'), ('EXPECTED_PATTERN', 'Not an issue - Expected pattern')], default='UNDER_REVIEW', max_length=32)),
                ('owner_name', models.CharField(blank=True, max_length=120)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('root_cause', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('extra_context', models.JSONField(blank=True, default=dict)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='auditpilot.controlcatalog')),
                ('recurrence_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrences', to='auditpilot.exceptionrecord')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='auditpilot.auditrun')),
            ],
            options={
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExceptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('note', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='auditpilot.exceptionrecord')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=40)),
                ('source_sheet', models.CharField(max_length=40)),
                ('source_row_number', models.PositiveIntegerField()),
                ('company_code', models.CharField(blank=True, max_length=64)),
                ('vendor_code', models.CharField(blank=True, max_length=64)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('fiscal_year', models.IntegerField(blank=True, null=True)),
                ('payment_document', models.CharField(blank=True, max_length=128)),
                ('accounting_document', models.CharField(blank=True, max_length=128)),
                ('payment_method', models.CharField(blank=True, max_length=128)),
                ('document_type', models.CharField(blank=True, max_length=128)),
                ('process_group', models.CharField(blank=True, max_length=128)),
                ('nature_of_transaction', models.CharField(blank=True, max_length=255)),
                ('status_code', models.CharField(blank=True, max_length=128)),
                ('status_description', models.CharField(blank=True, max_length=255)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('baseline_date', models.DateField(blank=True, null=True)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('payment_entry_date', models.DateField(blank=True, null=True)),
                ('payment_release_date', models.DateField(blank=True, null=True)),
                ('clearing_date', models.DateField(blank=True, null=True)),
                ('net_due_date', models.DateField(blank=True, null=True)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('amount_local', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_document', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('days_of_status', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_cycle_time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_processing_time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_key', models.CharField(db_index=True, max_length=40)),
                ('payment_key', models.CharField(db_index=True, max_length=40)),
                ('record_class', models.CharField(choices=[('base_transaction', 'Base transaction'), ('derived_result', 'Derived result line')], max_length=24)),
                ('record_fingerprint', models.CharField(db_index=True, max_length=40)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='auditpilot.auditrun')),
            ],
            options={
                'ordering': ['source_sheet', 'source_row_number'],
            },
        ),
        migrations.AddField(
            model_name='exceptionrecord',
            name='normalized_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='auditpilot.normalizedrecord'),
        ),
        migrations.CreateModel(
            name='SchemaSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=40)),
                ('version', models.PositiveIntegerField()),
                ('header_signature', models.CharField(max_length=64, unique=True)),
                ('headers_json', models.JSONField(default=list)),
                ('required_headers_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sheet_name', '-version'],
                'unique_together': {('sheet_name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='SheetRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('PASSED', 'Passed'), ('WARNING', 'Warning'), ('FAILED', 'Failed')], default='PASSED', max_length=16)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('normalized_row_count', models.PositiveIntegerField(default=0)),
                ('base_transaction_count', models.PositiveIntegerField(default=0)),
                ('derived_row_count', models.PositiveIntegerField(default=0)),
                ('schema_version', models.CharField(blank=True, max_length=32)),
                ('required_missing_json', models.JSONField(blank=True, default=list)),
                ('new_columns_json', models.JSONField(blank=True, default=list)),
                ('metrics_json', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_runs', to='auditpilot.auditrun')),
            ],
            options={
                'ordering': ['sheet_name'],
            },
        ),
        migrations.CreateModel(
            name='DQFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=16)),
                ('code', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dq_findings', to='auditpilot.auditrun')),
                ('sheet_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dq_findings', to='auditpilot.sheetrun')),
            ],
            options={
                'ordering': ['sheet_run__sheet_name', 'severity', 'code'],
            },
        ),
        migrations.AddField(
            model_name='auditrun',
            name='source_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='auditpilot.sourcefilearchive'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['run', 'entity'], name='auditpilot__run_id_a4cbee_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['run', 'record_class'], name='auditpilot__run_id_dbc169_idx'),
        ),
        migrations.AddIndex(
            model_name='exceptionrecord',
            index=models.Index(fields=['status', 'entity'], name='auditpilot__status_ba6840_idx'),
        ),
        migrations.AddIndex(
            model_name='exceptionrecord',
            index=models.Index(fields=['run', 'severity'], name='auditpilot__run_id_38f89a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sheetrun',
            unique_together={('run', 'sheet_name')},
        ),
    ]
