# Generated by Django 5.2.12 on 2026-04-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditpilot', '0002_seed_starter_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrun',
            name='processing_stage',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
